In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
movie=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movie.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movie.shape

(4803, 20)

In [5]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [6]:
credits.shape

(4803, 4)

In [7]:
movies=movie.merge(credits,on='title')
movies.shape

(4809, 23)

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [9]:
# columns we will keep
# genres
# id
# keywords
# overview   
# title 
# cast
# crew

In [10]:
movies=movies[['genres','id','keywords','overview','title','cast','crew']]

In [11]:
movies.isnull().sum()

genres      0
id          0
keywords    0
overview    3
title       0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
movies.iloc[1].genres

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [15]:
# bring above format to below form
# Adventure,Fantasy Action

In [16]:
import json
def convert(obj):
    list=[]
    for i in json.loads(obj):
        list.append(i['name'])
    return list

In [17]:
movies['genres']=movies['genres'].apply(convert)

In [18]:
movies.head(2)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [19]:
movies['keywords']=movies['keywords'].apply(convert)

In [20]:
movies.head(2)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [21]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [22]:
def convert1(obj):
    list=[]
    check=1
    for i in json.loads(obj):
        if check<=3:
            list.append(i['name'])
            check+=1
        else:
            break
    return list

In [23]:
movies['cast']=movies['cast'].apply(convert1)

In [24]:
movies.head(2)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [25]:
# crew

In [26]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [27]:
def convert2(obj):
    list=[]
    for i in json.loads(obj):
        if i['job']=='Director':
            list.append(i['name'])
            break
    return list

In [28]:
movies['crew']=movies['crew'].apply(convert2)

In [29]:
movies.head(4)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]

In [30]:
# overview

In [31]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [32]:
movies.head(3)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [33]:
# space removal

In [34]:
movies['cast']=movies['cast'].apply(lambda x:[i.replace(' ','')for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(' ','')for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(' ','')for i in x])
movies['genres']=movies['genres'].apply(lambda x:[i.replace(' ','')for i in x])

In [35]:
movies.head(3)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]

In [36]:
movies['tags']=movies['genres']+movies['keywords']+movies['overview']+movies['cast']+movies['crew']

In [37]:
movies.head(3)

,genres,id,keywords,overview,title,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[Action, Adventure, Crime, spy, basedonnovel, ..."

In [38]:
df=movies[['id','title','tags']]

In [39]:
df['tags']=df['tags'].apply(lambda x: ' '.join(x))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7632\1028912986.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x: ' '.join(x))

In [40]:
df['tags']=df['tags'].apply(lambda x: x.lower() )

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7632\718097810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x: x.lower() )

In [41]:
df.head(2)

,id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...

### Stemming

In [42]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [43]:
def stem(value):
    list1=[]
    for i in value.split():
        list1.append(ps.stem(i))
    return " ".join(list1)

In [44]:
df['tags']=df['tags'].apply(stem)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7632\4230616273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(stem)

In [49]:
df['tags'][0]

'action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. samworthington zoesaldana sigourneyweav jamescameron'

### Vectorization

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [51]:
vectors=cv.fit_transform(df['tags']).toarray()

In [52]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

### Cosine similarity

In [53]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity.shape
type(similarity)

numpy.ndarray

In [54]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ], shape=(4806,))

In [55]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329], shape=(4806,))

In [56]:
similarity[3]

array([0.07347184, 0.03883678, 0.06004806, ..., 0.03140371, 0.04852616,
       0.08633531], shape=(4806,))

In [57]:
sorted(similarity[1],reverse=True)

[np.float64(1.0),
 np.float64(0.4140043409440133),
 np.float64(0.27500954910846337),
 np.float64(0.2533201985524494),
 np.float64(0.20579830217101058),
 np.float64(0.20579830217101058),
 np.float64(0.18981415059132412),
 np.float64(0.18499891602515212),
 np.float64(0.17589669862367344),
 np.float64(0.17503501050350123),
 np.float64(0.17149858514250882),
 np.float64(0.17149858514250882),
 np.float64(0.17149858514250882),
 np.float64(0.16647802295407294),
 np.float64(0.16637806616154058),
 np.float64(0.16502459049611234),
 np.float64(0.16502459049611234),
 np.float64(0.16477051091432687),
 np.float64(0.16269784336399212),
 np.float64(0.1618740515220081),
 np.float64(0.1592324388246205),
 np.float64(0.1592324388246205),
 np.float64(0.1569197342897824),
 np.float64(0.1562904982411873),
 np.float64(0.15512630699850574),
 np.float64(0.15339299776947407),
 np.float64(0.15339299776947407),
 np.float64(0.15339299776947407),
 np.float64(0.15171652122725207),
 np.float64(0.15158476564770806),
 np.float64(0.15009383798227796),
 np.float64(0.14969623771302393),
 np.float64(0.14705882352941174),
 np.float64(0.14705882352941174),
 np.float64(0.14699878726500756),
 np.float64(0.14699878726500756),
 np.float64(0.1462544848254261),
 np.float64(0.1449427589131121),
 np.float64(0.1449427589131121),
 np.float64(0.1430397079704303),
 np.float64(0.14134285422946366),
 np.float64(0.14097096860865022),
 np.float64(0.14097096860865022),
 np.float64(0.140028008402801),
 np.float64(0.140028008402801),
 np.float64(0.1373087590952724),
 np.float64(0.1373087590952724),
 np.float64(0.1355815361366601),
 np.float64(0.1345345587992625),
 np.float64(0.1332593209305539),
 np.float64(0.1332593209305539),
 np.float64(0.13284223283101426),
 np.float64(0.13231403100624078),
 np.float64(0.1320196723968899),
 np.float64(0.1320196723968899),
 np.float64(0.1320196723968899),
 np.float64(0.13174886252731766),
 np.float64(0.12964074471043285),
 np.float64(0.12964074471043285),
 np.float64(0.12964074471043283),
 np.float64(0.12964074471043283),
 np.float64(0.1292719224987548),
 np.float64(0.1292719224987548),
 np.float64(0.1292719224987548),
 np.float64(0.12862393885688161),
 np.float64(0.12862393885688161),
 np.float64(0.12862393885688161),
 np.float64(0.12862393885688161),
 np.float64(0.1278274981412284),
 np.float64(0.1278274981412284),
 np.float64(0.12738595105969638),
 np.float64(0.12738595105969638),
 np.float64(0.12738595105969638),
 np.float64(0.1264304343560434),
 np.float64(0.1264304343560434),
 np.float64(0.1264304343560434),
 np.float64(0.12524485821702988),
 np.float64(0.12507819831856498),
 np.float64(0.12507819831856498),
 np.float64(0.12478354962115543),
 np.float64(0.12478354962115543),
 np.float64(0.12478354962115543),
 np.float64(0.12376844287208429),
 np.float64(0.12320822072673948),
 np.float64(0.12320822072673948),
 np.float64(0.12320822072673948),
 np.float64(0.12320822072673948),
 np.float64(0.12126781251816647),
 np.float64(0.12126781251816646),
 np.float64(0.12126781251816646),
 np.float64(0.12126781251816646),
 np.float64(0.12065379433217113),
 np.float64(0.12043434688555504),
 np.float64(0.12007302660701852),
 np.float64(0.12007302660701852),
 np.float64(0.11961783342433499),
 np.float64(0.11961783342433499),
 np.float64(0.11941628680530642),
 np.float64(0.11891287353862351),
 np.float64(0.11891287353862351),
 np.float64(0.11803342130469503),
 np.float64(0.11803342130469503),
 np.float64(0.11778571185788639),
 np.float64(0.11778571185788637),
 np.float64(0.11771773894935468),
 np.float64(0.11764705882352938),
 np.float64(0.11764705882352938),
 np.float64(0.11764705882352938),
 np.float64(0.11764705882352938),
 np.float64(0.11764705882352938),
 np.float64(0.11764705882352938),
 np.float64(0.11726446574911562),
 np.float64(0.11669000700233415),
 np.float64(0.11669000700233413),
 np.float64(0.11595420713048968),
 np.float64(0.11595420713048966),
 np.float64(0.11595420713048966),
 np.float64(0.11595420713048966),
 np.float64(0.11595420713048966),
 np.float64(0.11595420713048966),
 np.float64(0.11577058990186095),
 np.float64(0.11562432251572008),
 np.float64(0.11504474832710555),
 np.float64(0.11504474832710555),
 np.float64(0.11504474832710555),
 np.float64(0.11504474832710555),
 np.float64(0.11504474832710555),
 np.float64(0.11504474832710555),
 np.float64(0.11498609690941279),
 np.float64(0.11458731212852641),
 np.float64(0.1145873121285264),
 np.float64(0.11433239009500587),
 np.float64(0.11433239009500587),
 np.float64(0.11363310286178552),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11277677488692017),
 np.float64(0.11227217828476795),
 np.float64(0.11227217828476795),
 np.float64(0.11163607017227663),
 np.float64(0.11128297681493143),
 np.float64(0.1107018606925119),
 np.float64(0.11051407114136771),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.10984700727621793),
 np.float64(0.1097907187727647),
 np.float64(0.1097907187727647),
 np.float64(0.1097907187727647),
 np.float64(0.10969086361906959),
 np.float64(0.10969086361906959),
 np.float64(0.10969086361906957),
 np.float64(0.10969086361906957),
 np.float64(0.10969086361906957),
 np.float64(0.10890171046725802),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.10846522890932808),
 np.float64(0.1080339539253607),
 np.float64(0.1078676197944929),
 np.float64(0.10727978097782273),
 np.float64(0.10727978097782273),
 np.float64(0.10727978097782273),
 np.float64(0.10727978097782273),
 np.float64(0.10718661571406801),
 np.float64(0.10713431680111603),
 np.float64(0.10713431680111603),
 np.float64(0.10713431680111603),
 np.float64(0.10585122480499262),
 np.float64(0.10585122480499262),
 np.float64(0.10585122480499262),
 np.float64(0.10585122480499262),
 np.float64(0.10585122480499262),
 np.float64(0.10555008273018725),
 np.float64(0.10502100630210075),
 np.float64(0.10502100630210075),
 np.float64(0.10502100630210075),
 np.float64(0.10502100630210075),
 np.float64(0.10502100630210075),
 np.float64(0.10461315619318828),
 np.float64(0.10461315619318828),
 np.float64(0.10398629135096286),
 np.float64(0.10341753799900383),
 np.float64(0.10341753799900383),
 np.float64(0.10341753799900383),
 np.float64(0.10341753799900383),
 np.float64(0.10341753799900383),
 np.float64(0.10341753799900383),
 np.float64(0.10323001737691673),
 np.float64(0.10289915108550529),
 np.float64(0.10289915108550529),
 np.float64(0.10289915108550529),
 np.float64(0.10289915108550529),
 np.float64(0.10289915108550529),
 np.float64(0.10289915108550529),
 np.float64(0.10226199851298272),
 np.float64(0.10226199851298272),
 np.float64(0.10226199851298272),
 np.float64(0.10176568762666317),
 np.float64(0.10138954626279946),
 np.float64(0.10114434748483471),
 np.float64(0.10114434748483471),
 np.float64(0.10114434748483471),
 np.float64(0.10114434748483471),
 np.float64(0.10114434748483471),
 np.float64(0.10114434748483471),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944687),
 np.float64(0.10090091909944686),
 np.float64(0.10036195573796253),
 np.float64(0.10036195573796253),
 np.float64(0.10036195573796253),
 np.float64(0.10006255865485197),
 np.float64(0.10006255865485197),
 np.float64(0.10006255865485197),
 np.float64(0.10006255865485197),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766743),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09901475429766741),
 np.float64(0.09867967802605515),
 np.float64(0.0983611844205792),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09799919151000504),
 np.float64(0.09772038812426302),
 np.float64(0.09737260471306503),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09723055853282464),
 np.float64(0.09709195467257715),
 np.float64(0.09701425001453318),
 np.float64(0.09673824874398684),
 np.float64(0.09647549158488412),
 np.float64(0.09647549158488411),
 np.float64(0.09605842128561481),
 np.float64(0.09605842128561481),
 np.float64(0.09605842128561481),
 np.float64(0.09605842128561481),
 np.float64(0.09605842128561481),
 np.float64(0.09605842128561481),
 np.float64(0.09605842128561481),
 np.float64(0.0958706236059213),
 np.float64(0.0955394632947723),
 np.float64(0.0955394632947723),
 np.float64(0.09553946329477228),
 np.float64(0.09553946329477228),
 np.float64(0.09553946329477228),
 np.float64(0.09553946329477228),
 np.float64(0.09553946329477228),
 np.float64(0.09553946329477228),
 np.float64(0.09553946329477228),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09513029883089881),
 np.float64(0.09469425238482124),
 np.float64(0.0942285694863091),
 np.float64(0.0942285694863091),
 np.float64(0.0942285694863091),
 np.float64(0.0942285694863091),
 np.float64(0.09412207643723192),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.0939336436627724),
 np.float64(0.09356014857063996),
 np.float64(0.09335200560186731),
 np.float64(0.09335200560186731),
 np.float64(0.09335200560186731),
 np.float64(0.09335200560186731),
 np.float64(0.09335200560186731),
 np.float64(0.09335200560186731),
 np.float64(0.09335200560186731),
 np.float64(0.09249945801257606),
 np.float64(0.09249945801257606),
 np.float64(0.09249945801257606),
 np.float64(0.09249945801257606),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09240616554505461),
 np.float64(0.09193289141911525),
 np.float64(0.09166984970282112),
 np.float64(0.09166984970282112),
 np.float64(0.09166984970282112),
 np.float64(0.09166984970282112),
 np.float64(0.09166984970282112),
 np.float64(0.09166984970282112),
 np.float64(0.0914090530158913),
 np.float64(0.09095085938862485),
 np.float64(0.09095085938862485),
 np.float64(0.09095085938862485),
 np.float64(0.09095085938862485),
 np.float64(0.09086217008485092),
 np.float64(0.09086217008485092),
 np.float64(0.09086217008485092),
 np.float64(0.09086217008485092),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.09007546982220897),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08956221510397981),
 np.float64(0.08939981748151894),
 np.float64(0.0893088561378213),
 np.float64(0.0893088561378213),
 np.float64(0.0893088561378213),
 np.float64(0.0893088561378213),
 np.float64(0.08891787425369732),
 np.float64(0.08889132764189396),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08856148855400951),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08823529411764704),
 np.float64(0.08783257501821176),
 np.float64(0.08783257501821176),
 np.float64(0.08783257501821176),
 np.float64(0.08751750525175062),
 np.float64(0.08712136837380642),
 np.float64(0.08712136837380642),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08696565534786725),
 np.float64(0.08665671776277227),
 np.float64(0.08642716314028856),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.08574929257125441),
 np.float64(0.0850871259623034),
 np.float64(0.0850871259623034),
 np.float64(0.0850871259623034),
 np.float64(0.0850871259623034),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.08458258116519013),
 np.float64(0.0844400661841498),
 np.float64(0.0844400661841498),
 np.float64(0.0844400661841498),
 np.float64(0.0844400661841498),
 np.float64(0.08380754741901122),
 np.float64(0.08380754741901122),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08318903308077029),
 np.float64(0.08318903308077029),
 np.float64(0.08318903308077029),
 np.float64(0.08318903308077029),
 np.float64(0.08318903308077029),
 np.float64(0.08318903308077029),
 np.float64(0.08258401390153339),
 np.float64(0.08258401390153339),
 np.float64(0.08258401390153339),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08238525545716345),
 np.float64(0.08213292636386628),
 np.float64(0.08199200616907877),
 np.float64(0.08199200616907876),
 np.float64(0.08141255010133054),
 np.float64(0.08141255010133054),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08134892168199606),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08084520834544433),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08035073760083702),
 np.float64(0.08028956459037002),
 np.float64(0.08028956459037002),
 np.float64(0.07996162762590017),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07974522228289),
 np.float64(0.07962575371800423),
 np.float64(0.07961621941231024),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07938841860374446),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07868894753646336),
 np.float64(0.07860624762130128),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07817631049941041),
 np.float64(0.07817631049941041),
 np.float64(0.07817631049941041),
 np.float64(0.07756315349925287),
 np.float64(0.07756315349925287),

In [58]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.25038669783359574))]

In [60]:
list(enumerate(sorted(similarity[1],reverse=True)))

[(0, np.float64(1.0)),
 (1, np.float64(0.4140043409440133)),
 (2, np.float64(0.27500954910846337)),
 (3, np.float64(0.2533201985524494)),
 (4, np.float64(0.20579830217101058)),
 (5, np.float64(0.20579830217101058)),
 (6, np.float64(0.18981415059132412)),
 (7, np.float64(0.18499891602515212)),
 (8, np.float64(0.17589669862367344)),
 (9, np.float64(0.17503501050350123)),
 (10, np.float64(0.17149858514250882)),
 (11, np.float64(0.17149858514250882)),
 (12, np.float64(0.17149858514250882)),
 (13, np.float64(0.16647802295407294)),
 (14, np.float64(0.16637806616154058)),
 (15, np.float64(0.16502459049611234)),
 (16, np.float64(0.16502459049611234)),
 (17, np.float64(0.16477051091432687)),
 (18, np.float64(0.16269784336399212)),
 (19, np.float64(0.1618740515220081)),
 (20, np.float64(0.1592324388246205)),
 (21, np.float64(0.1592324388246205)),
 (22, np.float64(0.1569197342897824)),
 (23, np.float64(0.1562904982411873)),
 (24, np.float64(0.15512630699850574)),
 (25, np.float64(0.15339299776947407)),
 (26, np.float64(0.15339299776947407)),
 (27, np.float64(0.15339299776947407)),
 (28, np.float64(0.15171652122725207)),
 (29, np.float64(0.15158476564770806)),
 (30, np.float64(0.15009383798227796)),
 (31, np.float64(0.14969623771302393)),
 (32, np.float64(0.14705882352941174)),
 (33, np.float64(0.14705882352941174)),
 (34, np.float64(0.14699878726500756)),
 (35, np.float64(0.14699878726500756)),
 (36, np.float64(0.1462544848254261)),
 (37, np.float64(0.1449427589131121)),
 (38, np.float64(0.1449427589131121)),
 (39, np.float64(0.1430397079704303)),
 (40, np.float64(0.14134285422946366)),
 (41, np.float64(0.14097096860865022)),
 (42, np.float64(0.14097096860865022)),
 (43, np.float64(0.140028008402801)),
 (44, np.float64(0.140028008402801)),
 (45, np.float64(0.1373087590952724)),
 (46, np.float64(0.1373087590952724)),
 (47, np.float64(0.1355815361366601)),
 (48, np.float64(0.1345345587992625)),
 (49, np.float64(0.1332593209305539)),
 (50, np.float64(0.1332593209305539)),
 (51, np.float64(0.13284223283101426)),
 (52, np.float64(0.13231403100624078)),
 (53, np.float64(0.1320196723968899)),
 (54, np.float64(0.1320196723968899)),
 (55, np.float64(0.1320196723968899)),
 (56, np.float64(0.13174886252731766)),
 (57, np.float64(0.12964074471043285)),
 (58, np.float64(0.12964074471043285)),
 (59, np.float64(0.12964074471043283)),
 (60, np.float64(0.12964074471043283)),
 (61, np.float64(0.1292719224987548)),
 (62, np.float64(0.1292719224987548)),
 (63, np.float64(0.1292719224987548)),
 (64, np.float64(0.12862393885688161)),
 (65, np.float64(0.12862393885688161)),
 (66, np.float64(0.12862393885688161)),
 (67, np.float64(0.12862393885688161)),
 (68, np.float64(0.1278274981412284)),
 (69, np.float64(0.1278274981412284)),
 (70, np.float64(0.12738595105969638)),
 (71, np.float64(0.12738595105969638)),
 (72, np.float64(0.12738595105969638)),
 (73, np.float64(0.1264304343560434)),
 (74, np.float64(0.1264304343560434)),
 (75, np.float64(0.1264304343560434)),
 (76, np.float64(0.12524485821702988)),
 (77, np.float64(0.12507819831856498)),
 (78, np.float64(0.12507819831856498)),
 (79, np.float64(0.12478354962115543)),
 (80, np.float64(0.12478354962115543)),
 (81, np.float64(0.12478354962115543)),
 (82, np.float64(0.12376844287208429)),
 (83, np.float64(0.12320822072673948)),
 (84, np.float64(0.12320822072673948)),
 (85, np.float64(0.12320822072673948)),
 (86, np.float64(0.12320822072673948)),
 (87, np.float64(0.12126781251816647)),
 (88, np.float64(0.12126781251816646)),
 (89, np.float64(0.12126781251816646)),
 (90, np.float64(0.12126781251816646)),
 (91, np.float64(0.12065379433217113)),
 (92, np.float64(0.12043434688555504)),
 (93, np.float64(0.12007302660701852)),
 (94, np.float64(0.12007302660701852)),
 (95, np.float64(0.11961783342433499)),
 (96, np.float64(0.11961783342433499)),
 (97, np.float64(0.11941628680530642)),
 (98, np.float64(0.11891287353862351)),
 (99, np.float64(0.11891287353862351)),
 (100, np.float64(0.11803342130469503)),
 (101, np.float64(0.11803342130469503)),
 (102, np.float64(0.11778571185788639)),
 (103, np.float64(0.11778571185788637)),
 (104, np.float64(0.11771773894935468)),
 (105, np.float64(0.11764705882352938)),
 (106, np.float64(0.11764705882352938)),
 (107, np.float64(0.11764705882352938)),
 (108, np.float64(0.11764705882352938)),
 (109, np.float64(0.11764705882352938)),
 (110, np.float64(0.11764705882352938)),
 (111, np.float64(0.11726446574911562)),
 (112, np.float64(0.11669000700233415)),
 (113, np.float64(0.11669000700233413)),
 (114, np.float64(0.11595420713048968)),
 (115, np.float64(0.11595420713048966)),
 (116, np.float64(0.11595420713048966)),
 (117, np.float64(0.11595420713048966)),
 (118, np.float64(0.11595420713048966)),
 (119, np.float64(0.11595420713048966)),
 (120, np.float64(0.11577058990186095)),
 (121, np.float64(0.11562432251572008)),
 (122, np.float64(0.11504474832710555)),
 (123, np.float64(0.11504474832710555)),
 (124, np.float64(0.11504474832710555)),
 (125, np.float64(0.11504474832710555)),
 (126, np.float64(0.11504474832710555)),
 (127, np.float64(0.11504474832710555)),
 (128, np.float64(0.11498609690941279)),
 (129, np.float64(0.11458731212852641)),
 (130, np.float64(0.1145873121285264)),
 (131, np.float64(0.11433239009500587)),
 (132, np.float64(0.11433239009500587)),
 (133, np.float64(0.11363310286178552)),
 (134, np.float64(0.11357771260606365)),
 (135, np.float64(0.11357771260606365)),
 (136, np.float64(0.11357771260606365)),
 (137, np.float64(0.11357771260606365)),
 (138, np.float64(0.11277677488692017)),
 (139, np.float64(0.11277677488692017)),
 (140, np.float64(0.11277677488692017)),
 (141, np.float64(0.11277677488692017)),
 (142, np.float64(0.11227217828476795)),
 (143, np.float64(0.11227217828476795)),
 (144, np.float64(0.11163607017227663)),
 (145, np.float64(0.11128297681493143)),
 (146, np.float64(0.1107018606925119)),
 (147, np.float64(0.11051407114136771)),
 (148, np.float64(0.10984700727621793)),
 (149, np.float64(0.10984700727621793)),
 (150, np.float64(0.10984700727621793)),
 (151, np.float64(0.10984700727621793)),
 (152, np.float64(0.1097907187727647)),
 (153, np.float64(0.1097907187727647)),
 (154, np.float64(0.1097907187727647)),
 (155, np.float64(0.10969086361906959)),
 (156, np.float64(0.10969086361906959)),
 (157, np.float64(0.10969086361906957)),
 (158, np.float64(0.10969086361906957)),
 (159, np.float64(0.10969086361906957)),
 (160, np.float64(0.10890171046725802)),
 (161, np.float64(0.10846522890932808)),
 (162, np.float64(0.10846522890932808)),
 (163, np.float64(0.10846522890932808)),
 (164, np.float64(0.10846522890932808)),
 (165, np.float64(0.10846522890932808)),
 (166, np.float64(0.10846522890932808)),
 (167, np.float64(0.10846522890932808)),
 (168, np.float64(0.10846522890932808)),
 (169, np.float64(0.1080339539253607)),
 (170, np.float64(0.1078676197944929)),
 (171, np.float64(0.10727978097782273)),
 (172, np.float64(0.10727978097782273)),
 (173, np.float64(0.10727978097782273)),
 (174, np.float64(0.10727978097782273)),
 (175, np.float64(0.10718661571406801)),
 (176, np.float64(0.10713431680111603)),
 (177, np.float64(0.10713431680111603)),
 (178, np.float64(0.10713431680111603)),
 (179, np.float64(0.10585122480499262)),
 (180, np.float64(0.10585122480499262)),
 (181, np.float64(0.10585122480499262)),
 (182, np.float64(0.10585122480499262)),
 (183, np.float64(0.10585122480499262)),
 (184, np.float64(0.10555008273018725)),
 (185, np.float64(0.10502100630210075)),
 (186, np.float64(0.10502100630210075)),
 (187, np.float64(0.10502100630210075)),
 (188, np.float64(0.10502100630210075)),
 (189, np.float64(0.10502100630210075)),
 (190, np.float64(0.10461315619318828)),
 (191, np.float64(0.10461315619318828)),
 (192, np.float64(0.10398629135096286)),
 (193, np.float64(0.10341753799900383)),
 (194, np.float64(0.10341753799900383)),
 (195, np.float64(0.10341753799900383)),
 (196, np.float64(0.10341753799900383)),
 (197, np.float64(0.10341753799900383)),
 (198, np.float64(0.10341753799900383)),
 (199, np.float64(0.10323001737691673)),
 (200, np.float64(0.10289915108550529)),
 (201, np.float64(0.10289915108550529)),
 (202, np.float64(0.10289915108550529)),
 (203, np.float64(0.10289915108550529)),
 (204, np.float64(0.10289915108550529)),
 (205, np.float64(0.10289915108550529)),
 (206, np.float64(0.10226199851298272)),
 (207, np.float64(0.10226199851298272)),
 (208, np.float64(0.10226199851298272)),
 (209, np.float64(0.10176568762666317)),
 (210, np.float64(0.10138954626279946)),
 (211, np.float64(0.10114434748483471)),
 (212, np.float64(0.10114434748483471)),
 (213, np.float64(0.10114434748483471)),
 (214, np.float64(0.10114434748483471)),
 (215, np.float64(0.10114434748483471)),
 (216, np.float64(0.10114434748483471)),
 (217, np.float64(0.10090091909944687)),
 (218, np.float64(0.10090091909944687)),
 (219, np.float64(0.10090091909944687)),
 (220, np.float64(0.10090091909944687)),
 (221, np.float64(0.10090091909944687)),
 (222, np.float64(0.10090091909944687)),
 (223, np.float64(0.10090091909944687)),
 (224, np.float64(0.10090091909944686)),
 (225, np.float64(0.10036195573796253)),
 (226, np.float64(0.10036195573796253)),
 (227, np.float64(0.10036195573796253)),
 (228, np.float64(0.10006255865485197)),
 (229, np.float64(0.10006255865485197)),
 (230, np.float64(0.10006255865485197)),
 (231, np.float64(0.10006255865485197)),
 (232, np.float64(0.09901475429766743)),
 (233, np.float64(0.09901475429766743)),
 (234, np.float64(0.09901475429766743)),
 (235, np.float64(0.09901475429766743)),
 (236, np.float64(0.09901475429766743)),
 (237, np.float64(0.09901475429766743)),
 (238, np.float64(0.09901475429766743)),
 (239, np.float64(0.09901475429766743)),
 (240, np.float64(0.09901475429766743)),
 (241, np.float64(0.09901475429766743)),
 (242, np.float64(0.09901475429766743)),
 (243, np.float64(0.09901475429766743)),
 (244, np.float64(0.09901475429766741)),
 (245, np.float64(0.09901475429766741)),
 (246, np.float64(0.09901475429766741)),
 (247, np.float64(0.09901475429766741)),
 (248, np.float64(0.09901475429766741)),
 (249, np.float64(0.09901475429766741)),
 (250, np.float64(0.09901475429766741)),
 (251, np.float64(0.09901475429766741)),
 (252, np.float64(0.09867967802605515)),
 (253, np.float64(0.0983611844205792)),
 (254, np.float64(0.09799919151000504)),
 (255, np.float64(0.09799919151000504)),
 (256, np.float64(0.09799919151000504)),
 (257, np.float64(0.09799919151000504)),
 (258, np.float64(0.09799919151000504)),
 (259, np.float64(0.09799919151000504)),
 (260, np.float64(0.09799919151000504)),
 (261, np.float64(0.09799919151000504)),
 (262, np.float64(0.09799919151000504)),
 (263, np.float64(0.09799919151000504)),
 (264, np.float64(0.09772038812426302)),
 (265, np.float64(0.09737260471306503)),
 (266, np.float64(0.09723055853282464)),
 (267, np.float64(0.09723055853282464)),
 (268, np.float64(0.09723055853282464)),
 (269, np.float64(0.09723055853282464)),
 (270, np.float64(0.09723055853282464)),
 (271, np.float64(0.09723055853282464)),
 (272, np.float64(0.09723055853282464)),
 (273, np.float64(0.09723055853282464)),
 (274, np.float64(0.09723055853282464)),
 (275, np.float64(0.09709195467257715)),
 (276, np.float64(0.09701425001453318)),
 (277, np.float64(0.09673824874398684)),
 (278, np.float64(0.09647549158488412)),
 (279, np.float64(0.09647549158488411)),
 (280, np.float64(0.09605842128561481)),
 (281, np.float64(0.09605842128561481)),
 (282, np.float64(0.09605842128561481)),
 (283, np.float64(0.09605842128561481)),
 (284, np.float64(0.09605842128561481)),
 (285, np.float64(0.09605842128561481)),
 (286, np.float64(0.09605842128561481)),
 (287, np.float64(0.0958706236059213)),
 (288, np.float64(0.0955394632947723)),
 (289, np.float64(0.0955394632947723)),
 (290, np.float64(0.09553946329477228)),
 (291, np.float64(0.09553946329477228)),
 (292, np.float64(0.09553946329477228)),
 (293, np.float64(0.09553946329477228)),
 (294, np.float64(0.09553946329477228)),
 (295, np.float64(0.09553946329477228)),
 (296, np.float64(0.09553946329477228)),
 (297, np.float64(0.09513029883089881)),
 (298, np.float64(0.09513029883089881)),
 (299, np.float64(0.09513029883089881)),
 (300, np.float64(0.09513029883089881)),
 (301, np.float64(0.09513029883089881)),
 (302, np.float64(0.09513029883089881)),
 (303, np.float64(0.09513029883089881)),
 (304, np.float64(0.09513029883089881)),
 (305, np.float64(0.09513029883089881)),
 (306, np.float64(0.09513029883089881)),
 (307, np.float64(0.09469425238482124)),
 (308, np.float64(0.0942285694863091)),
 (309, np.float64(0.0942285694863091)),
 (310, np.float64(0.0942285694863091)),
 (311, np.float64(0.0942285694863091)),
 (312, np.float64(0.09412207643723192)),
 (313, np.float64(0.0939336436627724)),
 (314, np.float64(0.0939336436627724)),
 (315, np.float64(0.0939336436627724)),
 (316, np.float64(0.0939336436627724)),
 (317, np.float64(0.0939336436627724)),
 (318, np.float64(0.0939336436627724)),
 (319, np.float64(0.0939336436627724)),
 (320, np.float64(0.0939336436627724)),
 (321, np.float64(0.0939336436627724)),
 (322, np.float64(0.0939336436627724)),
 (323, np.float64(0.0939336436627724)),
 (324, np.float64(0.09356014857063996)),
 (325, np.float64(0.09335200560186731)),
 (326, np.float64(0.09335200560186731)),
 (327, np.float64(0.09335200560186731)),
 (328, np.float64(0.09335200560186731)),
 (329, np.float64(0.09335200560186731)),
 (330, np.float64(0.09335200560186731)),
 (331, np.float64(0.09335200560186731)),
 (332, np.float64(0.09249945801257606)),
 (333, np.float64(0.09249945801257606)),
 (334, np.float64(0.09249945801257606)),
 (335, np.float64(0.09249945801257606)),
 (336, np.float64(0.09240616554505461)),
 (337, np.float64(0.09240616554505461)),
 (338, np.float64(0.09240616554505461)),
 (339, np.float64(0.09240616554505461)),
 (340, np.float64(0.09240616554505461)),
 (341, np.float64(0.09240616554505461)),
 (342, np.float64(0.09240616554505461)),
 (343, np.float64(0.09240616554505461)),
 (344, np.float64(0.09240616554505461)),
 (345, np.float64(0.09193289141911525)),
 (346, np.float64(0.09166984970282112)),
 (347, np.float64(0.09166984970282112)),
 (348, np.float64(0.09166984970282112)),
 (349, np.float64(0.09166984970282112)),
 (350, np.float64(0.09166984970282112)),
 (351, np.float64(0.09166984970282112)),
 (352, np.float64(0.0914090530158913)),
 (353, np.float64(0.09095085938862485)),
 (354, np.float64(0.09095085938862485)),
 (355, np.float64(0.09095085938862485)),
 (356, np.float64(0.09095085938862485)),
 (357, np.float64(0.09086217008485092)),
 (358, np.float64(0.09086217008485092)),
 (359, np.float64(0.09086217008485092)),
 (360, np.float64(0.09086217008485092)),
 (361, np.float64(0.09007546982220897)),
 (362, np.float64(0.09007546982220897)),
 (363, np.float64(0.09007546982220897)),
 (364, np.float64(0.09007546982220897)),
 (365, np.float64(0.09007546982220897)),
 (366, np.float64(0.09007546982220897)),
 (367, np.float64(0.09007546982220897)),
 (368, np.float64(0.09007546982220897)),
 (369, np.float64(0.09007546982220897)),
 (370, np.float64(0.08956221510397981)),
 (371, np.float64(0.08956221510397981)),
 (372, np.float64(0.08956221510397981)),
 (373, np.float64(0.08956221510397981)),
 (374, np.float64(0.08956221510397981)),
 (375, np.float64(0.08956221510397981)),
 (376, np.float64(0.08956221510397981)),
 (377, np.float64(0.08956221510397981)),
 (378, np.float64(0.08956221510397981)),
 (379, np.float64(0.08956221510397981)),
 (380, np.float64(0.08939981748151894)),
 (381, np.float64(0.0893088561378213)),
 (382, np.float64(0.0893088561378213)),
 (383, np.float64(0.0893088561378213)),
 (384, np.float64(0.0893088561378213)),
 (385, np.float64(0.08891787425369732)),
 (386, np.float64(0.08889132764189396)),
 (387, np.float64(0.08856148855400951)),
 (388, np.float64(0.08856148855400951)),
 (389, np.float64(0.08856148855400951)),
 (390, np.float64(0.08856148855400951)),
 (391, np.float64(0.08856148855400951)),
 (392, np.float64(0.08856148855400951)),
 (393, np.float64(0.08856148855400951)),
 (394, np.float64(0.08856148855400951)),
 (395, np.float64(0.08823529411764704)),
 (396, np.float64(0.08823529411764704)),
 (397, np.float64(0.08823529411764704)),
 (398, np.float64(0.08823529411764704)),
 (399, np.float64(0.08823529411764704)),
 (400, np.float64(0.08823529411764704)),
 (401, np.float64(0.08823529411764704)),
 (402, np.float64(0.08823529411764704)),
 (403, np.float64(0.08823529411764704)),
 (404, np.float64(0.08823529411764704)),
 (405, np.float64(0.08823529411764704)),
 (406, np.float64(0.08783257501821176)),
 (407, np.float64(0.08783257501821176)),
 (408, np.float64(0.08783257501821176)),
 (409, np.float64(0.08751750525175062)),
 (410, np.float64(0.08712136837380642)),
 (411, np.float64(0.08712136837380642)),
 (412, np.float64(0.08696565534786725)),
 (413, np.float64(0.08696565534786725)),
 (414, np.float64(0.08696565534786725)),
 (415, np.float64(0.08696565534786725)),
 (416, np.float64(0.08696565534786725)),
 (417, np.float64(0.08696565534786725)),
 (418, np.float64(0.08696565534786725)),
 (419, np.float64(0.08696565534786725)),
 (420, np.float64(0.08696565534786725)),
 (421, np.float64(0.08696565534786725)),
 (422, np.float64(0.08696565534786725)),
 (423, np.float64(0.08696565534786725)),
 (424, np.float64(0.08665671776277227)),
 (425, np.float64(0.08642716314028856)),
 (426, np.float64(0.08574929257125441)),
 (427, np.float64(0.08574929257125441)),
 (428, np.float64(0.08574929257125441)),
 (429, np.float64(0.08574929257125441)),
 (430, np.float64(0.08574929257125441)),
 (431, np.float64(0.08574929257125441)),
 (432, np.float64(0.08574929257125441)),
 (433, np.float64(0.08574929257125441)),
 (434, np.float64(0.08574929257125441)),
 (435, np.float64(0.08574929257125441)),
 (436, np.float64(0.08574929257125441)),
 (437, np.float64(0.08574929257125441)),
 (438, np.float64(0.08574929257125441)),
 (439, np.float64(0.08574929257125441)),
 (440, np.float64(0.08574929257125441)),
 (441, np.float64(0.08574929257125441)),
 (442, np.float64(0.08574929257125441)),
 (443, np.float64(0.08574929257125441)),
 (444, np.float64(0.08574929257125441)),
 (445, np.float64(0.08574929257125441)),
 (446, np.float64(0.0850871259623034)),
 (447, np.float64(0.0850871259623034)),
 (448, np.float64(0.0850871259623034)),
 (449, np.float64(0.0850871259623034)),
 (450, np.float64(0.08458258116519013)),
 (451, np.float64(0.08458258116519013)),
 (452, np.float64(0.08458258116519013)),
 (453, np.float64(0.08458258116519013)),
 (454, np.float64(0.08458258116519013)),
 (455, np.float64(0.08458258116519013)),
 (456, np.float64(0.08458258116519013)),
 (457, np.float64(0.08458258116519013)),
 (458, np.float64(0.08458258116519013)),
 (459, np.float64(0.08458258116519013)),
 (460, np.float64(0.08458258116519013)),
 (461, np.float64(0.08458258116519013)),
 (462, np.float64(0.0844400661841498)),
 (463, np.float64(0.0844400661841498)),
 (464, np.float64(0.0844400661841498)),
 (465, np.float64(0.0844400661841498)),
 (466, np.float64(0.08380754741901122)),
 (467, np.float64(0.08380754741901122)),
 (468, np.float64(0.08346223261119858)),
 (469, np.float64(0.08346223261119858)),
 (470, np.float64(0.08346223261119858)),
 (471, np.float64(0.08346223261119858)),
 (472, np.float64(0.08346223261119858)),
 (473, np.float64(0.08346223261119858)),
 (474, np.float64(0.08346223261119858)),
 (475, np.float64(0.08346223261119858)),
 (476, np.float64(0.08346223261119858)),
 (477, np.float64(0.08346223261119858)),
 (478, np.float64(0.08346223261119858)),
 (479, np.float64(0.08346223261119858)),
 (480, np.float64(0.08346223261119858)),
 (481, np.float64(0.08346223261119858)),
 (482, np.float64(0.08346223261119858)),
 (483, np.float64(0.08346223261119858)),
 (484, np.float64(0.08346223261119858)),
 (485, np.float64(0.08346223261119858)),
 (486, np.float64(0.08318903308077029)),
 (487, np.float64(0.08318903308077029)),
 (488, np.float64(0.08318903308077029)),
 (489, np.float64(0.08318903308077029)),
 (490, np.float64(0.08318903308077029)),
 (491, np.float64(0.08318903308077029)),

In [61]:
def recommend(movie):
    index=df[df['title'] == movie].index[0]
    distances=similarity[index]
    movies=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies:
        print(df.iloc[i[0]].title)

In [62]:
import pickle
pickle.dump(df.to_dict(),open('df.pkl','wb'))

In [64]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [105]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [95]:
index=df[df['title'] == 'Batman'].index[0]   
index

np.int64(1360)

In [97]:
distances=similarity[index]
distances

array([0.05407381, 0.08574929, 0.05892557, ..., 0.        , 0.0952381 ,
       0.07624929], shape=(4806,))

In [98]:
movies=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
movies

[(1361, np.float64(0.9428090415820631)),
 (210, np.float64(0.4114755998989118)),
 (119, np.float64(0.3340765523905305)),
 (428, np.float64(0.3250056229832958)),
 (4529, np.float64(0.32242634688922367))]